name: build
run-name: ${{github.actor}} build
on:
  [ push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - run: mkdir ${{guthub.workspace}}/../build
      - run: cmake -DCMAKE_TOOLCHAIN_FILE:FILEPATH=${{github.workspace}}/vcpkg.cmake -S {{github.workspace}} -B ${{github.workspace}}/../build